### ISSUE TITLE
Setup Keycloak service

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#61]
**To-do**
- [ ] Set up locally (docker compose)
- [ ] Add postgres db (not to use internal Java db)
- [ ] Add helm chart

[Keycloak documentation](https://www.keycloak.org/getting-started/getting-started-docker)
[Helm](https://helm.sh/docs/) - NB check helm command-line tool.

Acceptance criteria:
- Keycloak is set up 
- Helm chart is validated against local cluster

**Comment by MariusJulius** [comment]
Need to be moved to the correct repo.

**Comment by DanBondarenko** [comment]
@thenouan Need to discuss way forward with you: (a) set up Helm chart from scratch, (b) fork from an existing Keycloak Helm chart (e.g. [Bitnami’s](https://github.com/bitnami/charts/tree/main/bitnami/keycloak), [Codecentric’s](https://github.com/codecentric/helm-charts/tree/master/charts/keycloak)), (c) use existing chart in our planned Terraform configuration with all relevant parameters specified. Option (c) makes the most sense to me.
